name: Netara

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  sast:
    name: SAST
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: p/typescript

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm install

      - name: Audit dépendances
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint

  pre-build:
    name: Pre-build
    runs-on: ubuntu-22.04
    needs: sast
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm install

      - name: Typecheck
        run: npm run astro check

  build:
    name: Build
    runs-on: ubuntu-22.04
    needs: pre-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  post-build:
    name: Post-build
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Vérification structure build
        run: |
          test -d dist/server && echo "✅ serveur présent"
          test -d dist/client && echo "✅ assets présents"
          test -f dist/server/entry.mjs && echo "✅ entrypoint présent"

      - name: Taille du bundle
        run: |
          echo "📦 Taille du build :"
          du -sh dist/

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist